name: ClusterDiarizer
num_workers: 0
sample_rate: 16000
batch_size: 64
device: cuda
verbose: true
diarizer:
  manifest_filepath: d:\dark_h14\Projects\Newton\bit-transcribe\model_configs\input_manifest.json
  out_dir: d:\dark_h14\Projects\Newton\bit-transcribe\tmp
  oracle_vad: false
  collar: 0.25
  ignore_overlap: true
  vad:
    model_path: vad_multilingual_marblenet
    external_vad_manifest: null
    parameters:
      window_length_in_sec: 0.63
      shift_length_in_sec: 0.01
      smoothing: false
      overlap: 0.5
      onset: 0.8
      offset: 0.6
      pad_onset: 0
      pad_offset: -0.05
      min_duration_on: 0
      min_duration_off: 0.6
      filter_speech_first: true
  speaker_embeddings:
    model_path: titanet_large
    parameters:
      window_length_in_sec:
      - 1.5
      - 1.25
      - 1.0
      - 0.75
      - 0.5
      shift_length_in_sec:
      - 0.75
      - 0.625
      - 0.5
      - 0.375
      - 0.1
      multiscale_weights:
      - 1
      - 1
      - 1
      - 1
      - 1
      save_embeddings: true
  clustering:
    parameters:
      oracle_num_speakers: false
      max_num_speakers: 8
      enhanced_count_thres: 80
      max_rp_threshold: 0.25
      sparse_search_volume: 30
      maj_vote_spk_count: false
      chunk_cluster_count: 50
      embeddings_per_chunk: 10000
  msdd_model:
    model_path: null
    parameters:
      use_speaker_model_from_ckpt: true
      infer_batch_size: 25
      sigmoid_threshold:
      - 0.7
      - 1.0
      seq_eval_mode: false
      split_infer: true
      diar_window_length: 50
      overlap_infer_spk_limit: 5
  asr:
    model_path: d:\dark_h14\Projects\Newton\bit-transcribe\model_data\ctc_gigaam.nemo
    parameters:
      asr_based_vad: false
      asr_based_vad_threshold: 1.0
      asr_batch_size: null
      decoder_delay_in_sec: null
      word_ts_anchor_offset: null
      word_ts_anchor_pos: start
      fix_word_ts_with_VAD: false
      colored_text: false
      print_time: true
      break_lines: false
    ctc_decoder_parameters:
      pretrained_language_model: null
      beam_width: 32
      alpha: 0.5
      beta: 2.5
    realigning_lm_parameters:
      arpa_language_model: null
      min_number_of_words: 3
      max_number_of_words: 10
      logprob_diff_threshold: 1.2
    batch_size: 10
